Implementation of Omniture / Heartbeat analytics into AMP. The plugin can be implemented by providing an `omniture` object to the player config.
Omniture can be configured with or without Heartbeat, and for both live and VOD content:

== 1. Standard Omniture

== 2. Heartbeat SDK

== 3. Live linear Tracking - Heartbeat

== 4. Using Adobe Launch

=== 4.1. Reference Your Adobe Launch Script

To use Media SDK alongside Adobe Launch, first you need to add a reference to your Adobe Launch script as described in Adobe's documentation:

=== 4.2. Properly Configure The AMP Omniture Plugin

The sample below shows how to configure the AMP Omniture Plugin to be used alongside Adobe Launch.
<pre class="prettyprint">
 var config = {
 plugins: {
 heartbeat: {
 enabled: true,
 resources: [ {
 // Be sure to add the Omniture Plugin
 src: "#{paths.plugins}/omniture/Omniture.js",
 type: "text/javascript"
 }
 ],
 // The launch.variableName atribute must be added
 // and match the one set on the adobe experience platform
 launch: {
 variableName: 'ADB'
 },
 // A full list of metadata keys can be found as part of ADB.Media.VideoMetadataKeys
 metadata: {
 "video": {
 "test": "foo",
 "brand": 'amp_player_hb_test',
 ADB.Media.VideoMetadataKeys.show: "myShow",
 ADB.Media.VideoMetadataKeys.season: "mySeason",
 ADB.Media.VideoMetadataKeys.episode: "myEpisode",
 ADB.Media.VideoMetadataKeys.assetId: "myAssetId",
 ADB.Media.VideoMetadataKeys.genre: "myGenre"
 },
 ad:{
 advertiser:"test ADVERTISER"
 }
 }
 }
 }
 };
</pre>

=== 4.3 Setting Temporal Type and Duration

When using Adobe Launch it is required to specify the `temporal type` and `duration` of the assets, since these values are required by the MediaSDK at initialization time. This values can be passed along the media configuration.
