=== Custom Events

Google Analytics Plugin for AMP supports a wide variarity of events, those events need to be mapped into `googleanalytics` config object, next you will need to fire such event by using `trackEvent` API.

The following sample shows a basic implementation of a custom event.

==== 1. Mapping

First, Add the custom event in the `googleanalytics` config, under `events` section. The custom event for this sample will be ads `skipped`, which should be fired everytime the user clicks on IMA skip button.

==== 2. Tracking

Once you have added the `skipped` event, you must bind it to player's events listener.

==== 3. Verify

Finally, you should be able to see this events coming through the Google Analytics dashboard.

=== Custom Dimmensions (Universal Analytics)

Custom dimmensions can be added through the `googleanalytics` configuration as follows.

You are all set once this was added in the events you want to track, supposing that the `googleanalytics` custom dimension exists or is defined on customer's google analytics account.
